### ISSUE TITLE
近期的目标和规划

### ISSUE THREAD

**Issue by pixcai** [JSHonkers/jshonkers.com#1]
JSHonkers的目标是成为最好的JavaScript技术讨论社区。和传统的社区网站不同的是：传统的社区网站关注点过于杂乱，从前端到后端，涉及甚多。我相信杂而不精，将毫无意义。所以在这里，在JSHonkers，一切都将只和JavaScript有关。无论是最新的技术，流行的框架还是编码过程中遇到的坑，在这里都能找到答案。这也是创建JSHonkers的意义！

目前，即将开始开发JSHonkers社区网站，关于网站的功能和规划，在这里先简述一下：

1、最近React、Vue、ES6很火，想必很多人都有去学习。这正好是一个机会，因此我打算JSHonkers先用React开发，让尽可能多的人参与进来，在开发的过程中再慢慢完善。
2、打算先做一个响应式的官网首页，让许多不了解的人能更好的了解我们。
3、做好首页之后，开发聊天室功能，让所有成员能即时聊天和沟通。
4、聊天室开发完成后，开发论坛系统，让所有人可以发帖与回帖或者留言。聊天室开发完成后，开始进行详细的后续功能开发和完善。

所以，近期要开发的功能和使用的技术包括以下：
1、首页（HTML5 + CSS3，目前不使用任何框架）
2、聊天室（socket.io）
3、论坛（React + MongoDB或React + Redis）

希望有兴趣的人能加入项目中来，一起参与讨论和开发，一起成长，Thanks！

**Comment by 1340641314** [comment]
响应式没有怎么做过

**Comment by pixcai** [comment]
响应式可以用现成的框架。目前首页只是暂时的，我觉得不需要用Bootstrap之类的，用一些简单的布局框架就够了，比如flexboxgrid.css之类的

**Comment by 1340641314** [comment]
go

**Comment by pixcai** [comment]
我来写聊天室好了，首页等等看有没有人开发。如果聊天室写好了还没人开发，你或者我再开发也可以

**Comment by 1340641314** [comment]
参与开发的需要先报名，然后才会拉进项目成员，格式比如：

擅长技能：webpack，react，vue，less，等前端开发
参与开发的时间：晚上8点至10点，周六，周日
参与的项目：聊天室开发


PS，主要的作用是简单的了解一下个人的情况，有助于协调开发。

**Comment by Batur24** [comment]
我有兴趣加入
熟悉jQuery／Bootstrap，了解angularJs1, React 前端；还有python后端
时间，晚上8点以后

**Comment by studentlove** [comment]
下半年都要出差，熟悉但不厉害，暂时帮不了什么忙。。

**Comment by wuyuejianjue** [comment]
我来做首页

**Comment by chickencyj** [comment]
如果项目中可以用到原生JS或者ES6,bootstrap,express+mongoose的话，或许可以帮点忙

**Comment by AyumiKai** [comment]
熟悉es6 react相关技术栈、koa2、jquery、bootstrap、webpack等，希望能出点微薄之力。

**Comment by wuyuejianjue** [comment]
擅长技能：javascript,jquery,css,bootstrap,angular1.x等前端技术
参与开发的时间：晚上9点至11点，周一至周六
参与的项目：首页开发

**Comment by Statfine** [comment]
有兴趣加入开发或者作为学习
擅长技能：React,material-ui, bootstrap
参与开发的时间：晚上9点以后都可以
参与的项目：首页开发

**Comment by pixcai** [comment]
首页为transition分支下的views文件夹下的index.pug文件，有兴趣开发的可以fork分支，开发完成后提交PR即可
