### ISSUE TITLE
代码和提问注意事项

### ISSUE THREAD

**Issue by pixcai** [JSHonkers/jshonkers.com#2]
1、关于代码：

为了能使Github上的任何一个人参与到项目中来，请不要在代码中使用除英语以外的任何语言。如果你的母语不是英语，请先用翻译软件翻译为英语，再写到代码中。如果有语法错误，擅长英语的成员可以提交修复。

2、关于Issues：

Issues中可以用中文。如果有问题需要提问，请先确保之前的Issues中没有相同的问题，以免同样的问题问多次。

**Comment by Batur24** [comment]
支持，文档也是英语吗？

**Comment by pixcai** [comment]
文档可以先弄中文的，毕竟参与的人基本都是国内的。如果有人想编写英文文档，我只想说：Just do it！
